name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip wheel
      - run: pip install bandit "black[jupyter]" codespell flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .
      - run: black --check . || true
      - run: codespell --ignore-words-list="fo,therefor"
      - run: flake8 --ignore=E203,F401,F403 --max-complexity=10
                    --max-line-length=125 --show-source --statistics .
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || pip install --editable . || pip install . || true
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py37-plus **/*.py || true
      - run: safety check
